variables:
  GL_GOLANG_VERSION: 1.20.4

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
- test
- build

include:
- template: Security/SAST.gitlab-ci.yml

sast:
  stage: test

.go_before_script:
  - mkdir -p /go/src/gitlab.com/${CI_PROJECT_PATH} /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/CI_PROJECT_PATH
  - ln -s /go/src/gitlab.com/${CI_PROJECT_PATH} /go/src/_/builds/${CI_PROJECT_NAME	}
  - make dep

# unit_tests:
#   image: golang:${GL_GOLANG_VERSION}
#   stage: test
#   script:
#     - make test

lint_code:
  image: golang:${GL_GOLANG_VERSION}
  stage: test
  script:
    - make lint

build:
  image: golang:${GL_GOLANG_VERSION}
  stage: build
  script:
    - make