name: Push to Container Registry

on:
    push:
        branches:
            - main
            - CDSTH-530-Update-git-workflow-to-build-HTTP-server-on-tag-of-version
        tags:
          - 'v*'

env:
    IMAGE_NAME: protocol-verifier-http-server
    DOCKERFILE_PATH: ./Dockerfile

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set lowercase image name
              run: echo "repository_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ env.repository_lowercase }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ${{ env.DOCKERFILE_PATH }}
                  push: true
                  # tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
